FILE="version.nfo"
FILE_INCREMENTAL="version.incremental"

VERSION_INFO=`cat "$FILE"`

VERSION_MAJOR=`echo $VERSION_INFO | cut -d "." -f 1`
VERSION_MINOR=`echo $VERSION_INFO | cut -d "." -f 2 | cut -d " " -f 1`
VERSION_INCREMENTAL=`cat "$FILE_INCREMENTAL"`
let VERSION_INCREMENTAL++;
echo $VERSION_INCREMENTAL > $FILE_INCREMENTAL

echo "$VERSION_MAJOR.$VERSION_MINOR build: $VERSION_INCREMENTAL" > $FILE
